<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id$
 */
return array (
  'Address' => '住所',
  'Admin Customers' => '顧客管理',
  'Administrate Categories' => 'カテゴリ管理',
  'Administrate your Products' => '製品管理',
  'Administration' => '管理',
  'Advanced Search' => '先進検索',
  'Amount' => '量',
  'Article categories'=>'商品のカテゴリ',
  'Article specifications'=>'商品の仕様',
  'Articles'=>'商品',
  'Billing Address' => 'ビリング住所',
  'Buy this items' => 'この項目を買う',
  'Cancel' => 'キャンセル',
  'Cart' => 'カート',
  'Categories' => 'カテゴリ',
  'Category' => 'カテゴリ',
  'Configure Cart' => 'カートの構成',
  'Create' => '作成',
  'Create Category' => 'カテゴリの作成',
  'Create a new Category' => '新規カテゴリの作成',
  'Create a new Product' => '新規製品の作成',
  'Customer' => '顧客',
  'Customers' => '顧客',
  'Database Connection is not working' => 'データベースに接続できません',
  'Delete Image' => '画像の削除',
  'Delivery Address' => '配送住所',
  'Email' => 'Eメール',
  'Filename' => 'ファイル名',
  'Firstname' => '名',
  'Images' => '画像',
  'Images for' => '画像',
  'Install Webshop' => 'Web店のインストール',
  'Lastname' => '姓',
  'List' => 'リスト',
  'Manage' => '管理',
  'Parent' => '親',
  'Pending Orders' => '実行されていない注文',
  'Phone' => '電話',
  'Product' => '製品',
  'Remove from Cart' => 'カートを空にする',
  'Save' => '格納',
  'Shop' => '店',
  'Title' => 'タイトル',
  'Update' => '修正',
  'Update Category' => 'カテゴリの修正',
  'Upload' => 'アップロード',
  'Upload Image' => '画像アップロード',
  'Upload new Image' => '新規画像アップロード',
  'Userid' => 'ユーザID',
  'View' => 'ビュー',
  'Webshop is not in Debug Mode' => 'Web店はデバッグモードでない',
  'Yii Webshop Installation' => 'Yii Web店のインストール',
  'Your Shopping Cart' => 'ショッピングカート',
  'Your Shopping Cart contains: ' => 'ショッピングカートの内容',
  'Your shopping Cart is empty.' => 'ショッピングカートは空',
  'images' => '画像',
  'of' => '',
  'Shipping methods' => '配送方法',
  'Payment methods' => '支払い方法',
  'Tax'=>'税',
  'Orders'=>'注文',
);
